import { APP_META, THEMES, OFFICE_GUIDES, METHODOLOGY } from './data/content.js';
import { CANDIDATES, REGISTRATION_CHANGES, getCandidate } from './data/candidates.js';
import { SOURCES, sourceById } from './data/sources.js';
import { searchCandidates } from './utils/search.js';

const app = document.querySelector('#app');
const state = { compare: JSON.parse(localStorage.getItem('mapa2026-compare') || '[]') };
const esc = (v='') => String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const fmt = d => { if(!d) return '—'; const p=d.split('-'); return p.length===3?`${p[2]}/${p[1]}/${p[0]}`:d; };
const initials = n => n.split(' ').slice(0,2).map(x=>x[0]).join('').toUpperCase();
const officeSlug = c => c.office==='Presidente'?'president':'governor';

function nav(active='home'){
  const items=[['home','⌂','Início'],['president','◈','Presidência'],['governor','BA','Bahia'],['compare','⇄','Comparar'],['explore','⌕','Explorar'],['learn','▤','Entenda'],['sources','↗','Fontes']];
  return items.map(([id,ic,label])=>`<a href="#/${id==='president'||id==='governor'?`candidates/${id}`:id}" class="nav-link ${active===id?'active':''}"><b>${ic}</b><span>${label}</span></a>`).join('');
}
function shell(content,active='home'){
  return `<div class="shell"><aside class="sidebar"><a class="brand" href="#/home"><span>ME</span><strong>MAPA ELEITORAL<small>2026</small></strong></a><nav>${nav(active)}</nav><div class="side-note">Fontes, contexto e evidências. Sem ranking.</div></aside><section class="workspace"><header class="topbar"><a href="#/home" class="mobile-brand"><span>ME</span><strong>Mapa 2026</strong></a><div class="update">Atualizado ${fmt(APP_META.lastUpdated)}</div><button class="icon-btn" data-search aria-label="Buscar">⌕</button></header><main>${content}</main></section><nav class="bottom-nav">${[['home','⌂','Início'],['president','◈','Candidatos'],['compare','⇄','Comparar'],['explore','⌕','Explorar'],['learn','▤','Entenda']].map(([id,ic,l])=>`<a href="#/${id==='president'?'candidates/president':id}" class="${active===id||(id==='president'&&active==='governor')?'active':''}"><b>${ic}</b><small>${l}</small></a>`).join('')}</nav></div><div id="overlay"></div>`;
}
function intro(kicker,title,text){return `<section class="intro"><span class="kicker">${kicker}</span><h1>${title}</h1><p>${text}</p></section>`;}
function sourceBadge(s){const map={official:'Fonte oficial',press:'Fonte complementar'};return `<span class="badge ${s?.evidenceClass||'press'}">${map[s?.evidenceClass]||'Fonte'}</span>`;}
function sourceMini(id){const s=sourceById(id); if(!s)return ''; return `<a class="source-mini" href="${s.url}" target="_blank" rel="noopener"><span>${sourceBadge(s)}<strong>${esc(s.name)}</strong><small>Consultada em ${fmt(s.consultedAt)}</small></span><b>↗</b></a>`;}
function evidenceBtn(c,kind,key){return `<button class="evidence-btn" data-evidence data-candidate="${c.id}" data-kind="${kind}" data-key="${esc(key)}">Ver evidência</button>`;}

function home(){
 const pres=CANDIDATES.filter(c=>c.office==='Presidente').length, gov=CANDIDATES.filter(c=>c.office==='Governador da Bahia').length;
 return shell(`<section class="hero"><span class="kicker">ELEIÇÕES BRASILEIRAS • 2026</span><h1>Informação eleitoral<br><em>sem placar.</em></h1><p>${APP_META.subtitle}</p><button class="hero-search" data-search>⌕ <span>Busque candidato, proposta ou tema</span></button><div class="trust"><span>✓ Fontes identificadas</span><span>✓ Sem recomendação</span><span>✓ Histórico de mudanças</span></div></section><section class="section"><h2>O que você quer consultar?</h2><div class="home-grid">${[['#/candidates/president','🇧🇷','Presidência',`${pres} chapas exibidas`],['#/candidates/governor','BA','Governo da Bahia',`${gov} candidaturas exibidas`],['#/compare','⇄','Comparar','Informações documentadas lado a lado'],['#/explore','⌕','Explorar','Pesquise por tema ou proposta']].map(x=>`<a class="home-card" href="${x[0]}"><i>${x[1]}</i><span><strong>${x[2]}</strong><small>${x[3]}</small></span><b>→</b></a>`).join('')}</div></section><section class="split"><article class="panel"><span class="kicker">CRITÉRIO</span><h2>Da afirmação à fonte.</h2><p>Cada proposta ou posição carregada aponta para a evidência usada. O resumo não substitui o documento integral.</p></article><article class="panel"><span class="kicker">IMPORTANTE</span><h2>Ausência não vira conclusão.</h2><p>“Não localizado nas fontes consultadas” não significa que a informação não exista.</p><a href="#/methodology">Ver metodologia →</a></article></section>${changes(3)}<div class="notice">ⓘ ${APP_META.disclaimer}</div>`,'home');
}
function changes(limit=10,scope=null){let arr=REGISTRATION_CHANGES.filter(x=>!scope||x.scope===scope).slice(0,limit); if(!arr.length)return ''; return `<section class="section"><div class="section-head"><div><span class="kicker">ALTERAÇÕES DOCUMENTADAS</span><h2>Mudanças de candidatura</h2></div></div><div class="change-list">${arr.map(x=>`<article><div><strong>${esc(x.person)}</strong><span>${esc(x.scope)}</span></div><b>${esc(x.status)}</b><p>${esc(x.summary)}</p><div>${x.sourceIds.map(sourceMini).join('')}</div></article>`).join('')}</div></section>`;}
function candidateCard(c){return `<article class="candidate-card" data-searchtext="${esc(`${c.name} ${c.party} ${c.number}`.toLowerCase())}"><a href="#/candidate/${c.id}" class="candidate-main"><div class="avatar">${initials(c.name)}</div><div><span class="office">${c.office}</span><h3>${esc(c.name)}</h3><p><strong>${esc(c.party)}</strong> • nº ${esc(c.number)}</p><small>Vice: ${esc(c.vice)}</small></div><b>→</b></a><button data-compare="${c.id}" class="compare-toggle">${state.compare.includes(c.id)?'✓ No comparador':'+ Comparar'}</button></article>`;}
function candidates(scope){const isP=scope==='president', office=isP?'Presidente':'Governador da Bahia', list=CANDIDATES.filter(c=>c.office===office), active=isP?'president':'governor';return shell(`${intro('CANDIDATURAS',isP?'Presidência da República':'Governo da Bahia',isP?'Chapas validadas nas fontes oficiais consultadas.':'Candidaturas deferidas exibidas conforme as fontes consultadas.')}<div class="toolbar"><label>⌕<input id="filterCandidates" placeholder="Buscar por nome, partido ou número"></label><span>${list.length} candidaturas</span></div><div class="candidate-grid">${list.map(candidateCard).join('')}</div>${changes(10,isP?'Presidência':'Governo da Bahia')}`,active);}
function candidate(id){const c=getCandidate(id);if(!c)return notFound();return shell(`<a class="back" href="#/candidates/${officeSlug(c)}">← Voltar</a><section class="profile"><div class="avatar big">${initials(c.name)}</div><div><span class="office">${c.office}</span><h1>${esc(c.name)}</h1><p><strong>${esc(c.party)}</strong> • nº ${esc(c.number)}</p><small>Vice: ${esc(c.vice)}</small><div class="profile-actions"><a href="${c.officialProfileUrl}" target="_blank" rel="noopener">Cadastro oficial ↗</a><button data-compare="${c.id}">${state.compare.includes(c.id)?'✓ No comparador':'+ Comparar'}</button></div></div></section><nav class="subnav"><a href="#propostas">Propostas</a><a href="#posicoes">Posições</a><a href="#historico">Histórico</a><a href="#fontes">Fontes</a></nav><section class="section" id="propostas"><div class="section-head"><div><span class="kicker">PLANO E DOCUMENTOS</span><h2>Propostas carregadas</h2></div><a href="${c.governmentPlanUrl}" target="_blank" rel="noopener">Documento oficial ↗</a></div><div class="proposal-grid">${c.proposals.length?c.proposals.map(p=>`<article class="proposal"><span>${esc(p.theme)}</span><h3>${esc(p.title)}</h3><p>${esc(p.summary)}</p><small>${esc(p.type)} • consultado ${fmt(p.consultedAt)}</small>${evidenceBtn(c,'proposal',p.id)}</article>`).join(''):'<div class="empty">Não localizado nas fontes consultadas.</div>'}</div></section><section class="section" id="posicoes"><span class="kicker">POSIÇÕES PÚBLICAS ENCONTRADAS</span><h2>Posições documentadas</h2><div class="position-list">${c.positions.length?c.positions.map(p=>`<article><div><span>${esc(p.theme)}</span><strong>${esc(p.label)}</strong></div><p>${esc(p.detail)}</p>${evidenceBtn(c,'position',p.theme)}</article>`).join(''):'<div class="empty">Não localizado nas fontes consultadas.</div>'}</div></section><section class="section" id="historico"><span class="kicker">HISTÓRICO DOCUMENTADO</span><h2>Linha do tempo</h2><div class="timeline">${c.timeline.map(t=>`<article><b>${t.year}</b><div><strong>${esc(t.title)}</strong><p>${esc(t.description)}</p></div></article>`).join('')}</div><div class="legal-note">Esta versão não apresenta “sem ocorrência” como sinônimo de ficha limpa. Registros jurídicos só devem ser incluídos após identificação segura do processo, órgão, situação atual e fonte oficial.</div></section><section class="section" id="fontes"><span class="kicker">RASTREABILIDADE</span><h2>Fontes deste perfil</h2><div class="source-list">${c.sources.map(sourceMini).join('')}</div></section>`,officeSlug(c));}
function compare(){const selected=state.compare.map(getCandidate).filter(Boolean);return shell(`${intro('COMPARADOR','Comparar candidaturas','Selecione de 2 a 3 candidaturas. O painel não escolhe vencedor e não atribui notas.')}<div class="compare-pickers">${[0,1,2].map(i=>`<select data-slot="${i}"><option value="">${i<2?'Selecione candidatura':'Terceira candidatura (opcional)'}</option>${CANDIDATES.map(c=>`<option value="${c.id}" ${selected[i]?.id===c.id?'selected':''}>${esc(c.name)} — ${esc(c.party)}</option>`).join('')}</select>`).join('')}</div>${selected.length?`<div class="compare-stack">${THEMES.map(theme=>{const rows=selected.map(c=>({c,items:[...c.proposals,...c.positions].filter(x=>x.theme===theme)}));if(!rows.some(r=>r.items.length))return '';return `<section class="compare-theme"><h2>${theme}</h2><div>${rows.map(r=>`<article><strong>${esc(r.c.name)}</strong>${r.items.length?r.items.map(x=>`<p><b>${esc(x.title||x.label)}</b><br>${esc(x.summary||x.detail)}</p>`).join(''):'<p>Não localizado nas fontes consultadas.</p>'}</article>`).join('')}</div></section>`}).join('')}</div>`:'<div class="empty large">Adicione candidaturas nos perfis ou use os seletores acima.</div>'}`,'compare');}
function explore(){return shell(`${intro('BUSCA GLOBAL','Explorar propostas e posições','Digite um assunto para localizar informações carregadas na base.')}<div class="explore-box"><label>⌕<input id="exploreInput" placeholder="Ex.: saúde, imposto, armas, IA, trabalho"></label><div class="chips">${['Saúde','Impostos','Segurança','Armas','Drogas','IA','Educação','Trabalho'].map(x=>`<button data-query="${x}">${x}</button>`).join('')}</div></div><div id="results"></div>`,'explore');}
function searchResults(q){if(!q)return '';const r=searchCandidates(CANDIDATES,q);const total=r.candidates.length+r.proposals.length+r.positions.length;if(!total)return `<div class="empty large">Nenhum resultado localizado na base carregada.</div>`;return `<section class="section"><h2>${total} resultado(s)</h2><div class="results">${r.candidates.map(c=>`<a href="#/candidate/${c.id}"><span>CANDIDATURA</span><strong>${esc(c.name)}</strong><small>${esc(c.party)} • ${esc(c.office)}</small></a>`).join('')}${r.proposals.map(({candidate:c,proposal:p})=>`<article><span>PROPOSTA • ${esc(p.theme)}</span><strong>${esc(c.name)}</strong><p>${esc(p.summary)}</p>${evidenceBtn(c,'proposal',p.id)}</article>`).join('')}${r.positions.map(({candidate:c,position:p})=>`<article><span>POSIÇÃO • ${esc(p.theme)}</span><strong>${esc(c.name)} — ${esc(p.label)}</strong><p>${esc(p.detail)}</p>${evidenceBtn(c,'position',p.theme)}</article>`).join('')}</div></section>`;}
function learn(){return shell(`${intro('ENTENDA O CARGO','O que cada cargo pode fazer?','Promessas eleitorais não significam execução automática. Competências e limites importam.')}<div class="guide-grid">${Object.values(OFFICE_GUIDES).map(g=>`<article class="guide"><h2>${esc(g.title)}</h2><h3>Pode atuar em</h3><ul>${g.canDo.map(x=>`<li>${esc(x)}</li>`).join('')}</ul><h3>Limites e dependências</h3><ul>${g.limits.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></article>`).join('')}</div><div class="notice">Uma proposta pode depender de Congresso, Assembleia, orçamento, regulamentação, municípios, União ou decisão judicial.</div>`,'learn');}
function sources(){return shell(`${intro('TRANSPARÊNCIA','Fontes consultadas','Abra a fonte original e confira a informação no contexto completo.')}<div class="source-list big">${SOURCES.map(s=>`<a class="source-card" href="${s.url}" target="_blank" rel="noopener"><div>${sourceBadge(s)}<h3>${esc(s.name)}</h3><p>${esc(s.note||'')}</p><small>${esc(s.category)} • consultada ${fmt(s.consultedAt)}</small></div><b>↗</b></a>`).join('')}</div>`,'sources');}
function methodology(){return shell(`${intro('METODOLOGIA','Como o painel trata informação política','Critérios editoriais para reduzir inferências, distorções e confusão entre fatos diferentes.')}<div class="method-grid">${METHODOLOGY.map(m=>`<article><h2>${esc(m.title)}</h2><p>${esc(m.text)}</p></article>`).join('')}</div><div class="panel"><h2>Regra de ouro</h2><p>O painel organiza evidências. A interpretação e a decisão pertencem ao eleitor.</p></div>`,'sources');}
function notFound(){return shell(`<div class="empty large"><h1>Página não encontrada</h1><a href="#/home">Voltar ao início</a></div>`);}

function openEvidence(btn){const c=getCandidate(btn.dataset.candidate);if(!c)return;const item=btn.dataset.kind==='proposal'?c.proposals.find(x=>x.id===btn.dataset.key):c.positions.find(x=>x.theme===btn.dataset.key);if(!item)return;const root=document.querySelector('#overlay');root.innerHTML=`<div class="overlay" data-close><section class="sheet"><div class="sheet-head"><div><span class="kicker">EVIDÊNCIA</span><h2>${esc(item.title||item.theme)}</h2></div><button data-close>×</button></div><p>${esc(item.summary||item.detail)}</p><div class="source-list">${item.sourceIds.map(sourceMini).join('')}</div><div class="legal-note">O resumo não substitui a leitura do documento integral.</div></section></div>`;root.querySelectorAll('[data-close]').forEach(x=>x.addEventListener('click',e=>{if(e.target===x)root.innerHTML=''}));}
function openSearch(){const root=document.querySelector('#overlay');root.innerHTML=`<div class="overlay" data-close><section class="search-sheet"><div class="sheet-head"><h2>Busca global</h2><button data-close>×</button></div><label>⌕<input id="globalSearch" autofocus placeholder="Candidato, partido, proposta ou tema"></label><div id="globalResults"></div></section></div>`;root.querySelectorAll('[data-close]').forEach(x=>x.addEventListener('click',e=>{if(e.target===x)root.innerHTML=''}));const input=root.querySelector('#globalSearch');setTimeout(()=>input.focus(),30);input.addEventListener('input',()=>root.querySelector('#globalResults').innerHTML=searchResults(input.value));}
function bind(){document.querySelectorAll('[data-search]').forEach(x=>x.addEventListener('click',openSearch));document.querySelectorAll('[data-evidence]').forEach(x=>x.addEventListener('click',()=>openEvidence(x)));document.querySelectorAll('[data-compare]').forEach(x=>x.addEventListener('click',()=>{const id=x.dataset.compare;if(state.compare.includes(id))state.compare=state.compare.filter(v=>v!==id);else if(state.compare.length<3)state.compare.push(id);localStorage.setItem('mapa2026-compare',JSON.stringify(state.compare));render();}));document.querySelectorAll('[data-slot]').forEach(x=>x.addEventListener('change',()=>{const i=Number(x.dataset.slot),a=[...state.compare];if(x.value)a[i]=x.value;else a.splice(i,1);state.compare=[...new Set(a.filter(Boolean))].slice(0,3);localStorage.setItem('mapa2026-compare',JSON.stringify(state.compare));render();}));const f=document.querySelector('#filterCandidates');if(f)f.addEventListener('input',()=>document.querySelectorAll('.candidate-card').forEach(c=>c.hidden=!c.dataset.searchtext.includes(f.value.toLowerCase())));const ex=document.querySelector('#exploreInput');if(ex)ex.addEventListener('input',()=>document.querySelector('#results').innerHTML=searchResults(ex.value));document.querySelectorAll('[data-query]').forEach(b=>b.addEventListener('click',()=>{const ex=document.querySelector('#exploreInput');ex.value=b.dataset.query;document.querySelector('#results').innerHTML=searchResults(ex.value);}));}
function render(){const h=location.hash||'#/home';let html;if(h.startsWith('#/candidate/'))html=candidate(h.split('/')[2]);else if(h==='#/candidates/president')html=candidates('president');else if(h==='#/candidates/governor')html=candidates('governor');else if(h==='#/compare')html=compare();else if(h==='#/explore')html=explore();else if(h==='#/learn')html=learn();else if(h==='#/sources')html=sources();else if(h==='#/methodology')html=methodology();else html=home();app.innerHTML=html;bind();window.scrollTo({top:0,behavior:'instant'});}
window.addEventListener('hashchange',render);render();
